schema_version: 1

context:
  name: chemdiagrams
  version: "0.5.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8aeffdc353fd86dc45ce5ac49a96f971ad084e8a6c995523917beaaa9b855813

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - matplotlib-base >=3.7
    - numpy >=1.23
    - scipy >=1.10

tests:
  - python:
      imports:
        - chemdiagrams
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Publication-quality reaction energy diagrams for computational chemistry
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Tonner-Zech-Group/chem-diagrams

extra:
  recipe-maintainers:
    - jan-janssen
